name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pyflakes
      uses: lgeiger/pyflakes-action@v1.0.1
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.761
      with:
        # File or directory to run mypy on
        path: tvnamer
